Adding Dock Manager with Data Analysis sample
IgniteUI/ASP.NET-Core-Samples pull request #2
Opened 2020-07-16 09:06 UTC by HristoP96

Closes #1

2020-07-17 07:14 UTC, hanastasov submitted a review, later dismissed

2020-07-20 09:41 UTC, zdrawku requested changes
Well done, Hristo! Could you also add a brief description of the app - part of the solution main README.md. Also, it would be good to update the application README.md with an explanation about:
- how to start it (build the solution, install the dependencies, start the client app if needed and etc.)
- how the app is structured - what's covered with the Client app and what's the server part responsible for.

2020-07-20 13:32 UTC, HristoP96 commented
> Well done, Hristo! Could you also add a brief description of the app - part of the solution main README.md. Also, it would be good to update the application README.md with an explanation about:
> 
> * how to start it (build the solution, install the dependencies, start the client app if needed and etc.)
> * how the app is structured - what's covered with the Client app and what's the server part responsible for.

@zdrawku The requested changes are now available

2020-07-20 13:44 UTC, zdrawku approved these changes

2020-07-20 13:49 UTC, merged